### PR TITLE
Await GAID before targeting and identify 

### LINKED ISSUE #37: await gaid on identify and prepend to identify and targeting API
# Objectives
1. Await gaid before calling identify API - since the API is asynchronous anyway this await should happen on the background thread without blocking the main thread. 
2. If possible let's add a timeout of 3 seconds if it fails to be retrieved before that.  So that we guarantee it does not freeze. 
3. Prepend gaid as the very first identifier in the list of identifiers we send in the identify and targeting array of identifiers.
4. If it is also added by the user as part of the identifiers list - remove the duplicate - only send the one retrieved from the system API prepended to the list.
5. Add a test verifying that it is prepended when gaid is available (authorized) and not disabled by the user through config.
6. Add a test verifying that it is not pretended either when it is disabled in the config or when unavailable due to not authorized in the system (f.e. due to limit ad tracking).

### PR DESCRIPTION
**Pull request by ValentinPostindustria**
Closes #37.

### CODE REVIEW

File: android_sdk/src/main/java/co/optable/sdk/core/IdentifiersEncoder.kt [hunk 1]
```diff
@@ -34,7 +34,11 @@ internal class IdentifiersEncoder(
     fun encode(identifiers: List<OptableIdentifier>): List<String> {
         val result = mutableListOf<String>()
 
-        var containsCustomGaid = false
+        val googleAdId = googleAdIdManager.getId()
+        if (googleAdId != null) {
+            result.addIfNotNull(GAID, googleAdId, ::trim)
```
Comment (zapo) [inline android_sdk/src/main/java/co/optable/sdk/core/IdentifiersEncoder.kt]: Should we `::normalize` here as well similarly to what we do for user provided GAID?

File: android_sdk/src/main/java/co/optable/sdk/core/IdentifiersEncoder.kt [hunk 2]
```diff
@@ -51,8 +55,9 @@ internal class IdentifiersEncoder(
                 is OptableIdentifier.Utiq -> result.addIfNotNull(UTIQ, identifier.value, ::normalize)
 
                 is OptableIdentifier.GoogleGaid -> {
-                    result.addIfNotNull(GAID, identifier.value, ::normalize)
-                    containsCustomGaid = true
+                    if (googleAdId == null) {
```
Comment (zapo) [inline android_sdk/src/main/java/co/optable/sdk/core/IdentifiersEncoder.kt]: I see the requirements in #37 states we should override the user provided value with system detected, but I thought we were going to keep both, cc @jrosendahl-opt

**Review by zapo — COMMENTED** [review]
LGTM

**Review by zapo — APPROVED** [review]
